### ISSUE TITLE
Issues with chromedriver

### ISSUE THREAD

**Issue by RuthlessRuler** [VikasRana/bitdegree#1]
Getting some Chromedriver problem. Its located in E:\chromedriver.exe.
here how i placed it in .py file : driver = webdriver.Chrome("E:\\chromedriver.exe")
 The Error:
`Traceback (most recent call last):
  File "C:\Users\Kunal Agrawal\Downloads\bitdegree-master\bitdegree.py", line 7, in <module>
    driver = webdriver.Chrome("E:\\chromedriver.exe")
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=`

**Comment by RuthlessRuler** [comment]
Installed Chrome and it worked!
